development:
  # address: 'smtp.gmail.com'
  address: "smtp.mailgun.org"
  port: "587"
  domain: 'rate-service.com'
  authentication: "plain"
  user_name: <%= ENV['MAILGUN_USERNAME'] %>
  password: <%= ENV['MAILGUN_PASSWORD'] %>
  enable_starttls_auto: true
production:
  address: "smtp.mailgun.org"
  port: "587"
  domain: <%= ENV['DOMAIN'] %>
  authentication: "plain"
  user_name: <%= ENV['MAILGUN_USERNAME'] %>
  password: <%= ENV['MAILGUN_PASSWORD'] %>
  enable_starttls_auto: true
