# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0c66aa0977ce3be18fed91a16422352203edfc97ac7dc89d8f52af79cab7b8294f6862a51fd87e9a798c73f8907aec378bafed5a475dc7f201575f8bd104649

test:
  secret_key_base: acc88f79181d724ec86855c71479af6fa1ff25c4237bb865725140579685a6c097d8b42e7f83e4c5fc3a061d0d203037d03565388cb268f2a5a833b5eedc4673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
